POST http://localhost:8080/goals/add
Content-Type: application/json

{
  "name": "test",
  "description": "una descripcion pendeja",
  "timeEnd": "2021-08-02",
  "start": "2022-5-13",
  "user": "roku_js"
}